version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./backend/backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nestjs_app
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: